### ISSUE TITLE
【功能建议】能否在扫码登录之后把ck绑定的了所有游戏的uid都保存到数据库

### ISSUE THREAD

**Issue by mengluo04** [TimeRainStarSky/Yunzai-genshin#12]
目前只有原神，绝区零，星铁的，存起来方便其他插件调用。
我看了逍遥插件那边扫码登录之后是调用的/genshin/model/user.js的的bing方法传入ck，具体绑定是由genshin实现的

**Comment by TimeRainStarSky** [comment]
https://github.com/yoimiya-kokomi/Miao-Yunzai/issues/new
